//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.17929
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DocumRoller {
	
	
	public partial class SettingsDocumRoller {
		
		protected System.Web.UI.UserControl lblItemToShow;
		
		protected System.Web.UI.WebControls.TextBox txtItemToShow;
		
		protected System.Web.UI.UserControl lblSortField;
		
		protected System.Web.UI.WebControls.DropDownList ddlSortField;
		
		protected System.Web.UI.UserControl lblSortOrder;
		
		protected System.Web.UI.WebControls.CheckBox chkSortOrder;
	}
}
