//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.17929
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DocumRoller {
	
	
	public partial class ViewDocumRoller {
		
		protected System.Web.UI.WebControls.DataList lstContent;
		
		protected System.Web.UI.WebControls.HyperLink lnkDocument;
		
		protected System.Web.UI.WebControls.Label lblContent;
		
		protected System.Web.UI.WebControls.Label lblCreatedOnDate;
		
		protected System.Web.UI.WebControls.Label lblLastModifiedOnDate;

		protected System.Web.UI.WebControls.HyperLink linkRss;


	}
}
